services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/config/custom.ini:/usr/share/grafana/conf/custom.ini
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - NordChargerNetwork

volumes:
  grafana-storage:

networks:
  NordChargerNetwork:
    external: false
